### ISSUE TITLE
UAIC NLP Resources and Tools

### ISSUE THREAD

**Issue by DinuGanea** [radsimu/UaicNlpToolkit#1]
Hello,

thank you for sharing your code with the open source community!

The list of tools published on the following website: http://nlptools.info.uaic.ro/Resources.jsp is unfortunately not totally covered by this project.  

Moreover, the link specified on the website for accessing the tools and resources doesn't work either. 

Could you please add the missing tools to the project, or provide a working link to the specified tools and resources, if it's still possible, of course. 

Best Regards,
Dinu

**Comment by radsimu** [comment]
Hi. There is no plan for adding all the resources from the url you provided here. Right now, it contains the POS tagger, and GGS, which is required by the POS tagger and which can be used for creating other tools as well. There is also the plan to include the dependency parser in here at some point. But no plan to go further than that right now
